### ISSUE TITLE
Spinlock during loading

### ISSUE THREAD

**Issue by szarnyasg** [RapidsAtHKUST/RapidMatch#2] opened 2021-03-27 03:26 UTC
Hi,

I'm trying to load an LDBC-based data file to RapidMatch: https://www.dropbox.com/s/cqebtyvms07h6rv/ldbc-0.1.graph.zip?dl=0

```bash
./RapidMatch.out -d ldbc-0.1.graph -q person_triangle.graph -time_limit 5
```

This command spinlocks on `Load graphs` and is not killed even after the timeout passes.

```console
Command Line:
        Data Graph CSR: 
        Data Graph: ldbc-0.1.graph
        Query Graph: person_triangle.graph
        Order Type: nd
        Export Plan Path: 
        Import Plan Path: 
        Output Limit: MAX
        Time Limit (seconds): 5
        Order Num: 100
        Input Order: 
        Enable Preprocessor: true
--------------------------------------------------------------------
Configuration:
        Relation Structure: Encoded trie relation
        Embedding Structure: Subgraph Isomorphism 
        Count Results: False
        Hybrid Set Intersection: Enable
        SIMD Set Intersection: AVX2
        Hash Table Ratio of Pair-wise Join: 1.2
        Intersection Cache: Disabled
        Failing Set Pruning: Enabled
        Output Optimization: Enabled
        Sparse Bitmap: Disabled
--------------------------------------------------------------------
Load graphs...
```

I tried various settings such as turning preprocesing on, adding `nd` ordering but these did not make a difference.

It is possible that there is an error in the `.graph` query file but I'm unable to pinpoint it.

Is there a verbose/debug configuration for RapidMatch that I could activate to figure out where and why this spinlock occurs?

Gabor

**Comment by szarnyasg** [comment] 2021-03-27 15:33
It turns out my `.graph` file was indeed incorrect and (I mixed up target the vertex labels for some edges in my conversion script).
I'm leaving the issue open if you'd like to investigate with the example file -- but feel free to close this issue.

**Comment by shixuansun** [comment] 2021-03-28 10:23
> It turns out my `.graph` file was indeed incorrect and (I mixed up target the vertex labels for some edges in my conversion script).
> I'm leaving the issue open if you'd like to investigate with the example file -- but feel free to close this issue.

Hi,

Thanks for your question.

Do you mean that the issue is caused by the script and the program works well after fixing the script? If so, I will close the issue. If not, could you please provide me the test case such that I can repro the problem and fix it?

**Comment by szarnyasg** [comment] 2021-03-28 11:45
@shixuansun Yes – I fixed the conversion script, now RapidMatch can load the graph and produce the correct results.

**Comment by shixuansun** [comment] 2021-03-28 11:47
> @shixuansun Yes – I fixed the conversion script, now RapidMatch can load the graph and produce the correct results.

OK. Thanks for your update. Then, I will close this issue.

**Closed as completed** 2021-03-28 11:48 UTC
